[package]
name = "concierge"
version = "0.1.0"
authors = ["An Tran <avarelpm@gmail.com>"]
edition = "2018"

[dependencies]
# Async support
futures = "0.3.5"
# Async runtime
tokio = { version = "0.2", default-features = false, features = ["io-std", "macros", "stream", "time", "fs"] }
tokio-util = { version = "0.3.1", default-features = false, features = ["codec"] }
# WebSocket implementation
tokio-tungstenite = "0.10.1"
# Concurrent map, deadlock free for multithreaded peace of mind
dashmap = "4.0.0-rc6"
# Fast multithreaded MPSC channels
flume = "0.7.1"
# Ergonomic error handling
anyhow = "1.0.31"
# Serialization framework
serde_json = "1.0.55"
serde = { version = "1.0.112", features = ["derive"] }
# Logging capabilities
log = "0.4.8"
env_logger = "0.7.1"
# Static file server
hyper = "0.13.6"

# Developer dependences, not present in src code
[dev-dependencies]
url = "2.0.0"